# Generated by Django 2.0 on 2019-01-08 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_Filename', models.CharField(default='', max_length=20, verbose_name='文件名称')),
                ('models_Filedepartment', models.CharField(default='', max_length=20, verbose_name='BUH')),
                ('models_Filedes', models.TextField(default='', verbose_name='描述')),
                ('models_Fileusedfor', models.CharField(default='', max_length=20, verbose_name='人数')),
                ('models_Fileupload', models.FileField(max_length=1000, upload_to='file/%Y/%m', verbose_name='文件')),
                ('models_Updated_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
