# Generated by Django 2.0 on 2019-01-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharefile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addfilemodel',
            options={'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
        migrations.AddField(
            model_name='addfilemodel',
            name='models_clicknum',
            field=models.IntegerField(default=0, verbose_name='下载次数'),
        ),
    ]
